# Generated by Django 2.0.3 on 2018-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181102_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(db_column='Sid', primary_key=True, serialize=False),
        ),
    ]
