# Generated by Django 2.0.3 on 2018-11-05 03:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181102_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(db_column='Cid', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('pick_time', models.DateTimeField(verbose_name='date picked')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Course'),
            preserve_default=False,
        ),
    ]
