# Generated by Django 2.0.3 on 2018-11-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181105_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='courses',
        ),
    ]
