# Generated by Django 2.0.3 on 2018-11-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('id',)},
        ),
    ]
